FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 50283
EXPOSE 44393

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["Web.App/Web.App.csproj", "Web.App/"]
RUN dotnet restore "Web.App/Web.App.csproj"
COPY . .
WORKDIR "/src/Web.App"
RUN dotnet build "Web.App.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Web.App.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Web.App.dll"]